### ISSUE TITLE
Main server stops responding

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#156]
After some time the server hangs/blocks. We are running on one process, so we have a fair chance of finding out what is causing these hangs. Try using two browsers and try combinations of scenario's. I have tried unlimited search '*' in combination with R/qtl, corr. matrix, pylmm, etc. If slow, all recover fine (so far).

Note that the main server may be getting requests over the internet. The mechanical Rob will also be great at stress testing the server.

**Comment by pjotrp** [comment]
I think we ran out of connections. One way to check MySQL connection pools is in a MySQL client with:

 SHOW STATUS WHERE variable_name LIKE "Threads_%" OR variable_name = "Connections";

| Threads_connected | 4     |

The number of threads connected matters and should not go up over time.

**Comment by pjotrp** [comment]
I am stress testing the database and large searches are a cause for consuming connections.

**Comment by pjotrp** [comment]
This should be resolved now we are running on gunicorn.

**Comment by pjotrp** [comment]
Actually, the problem persists.

**Comment by pjotrp** [comment]
```
[2018-03-31 12:22:17,110] ERROR in logger: .handle_bad_request: 12:22:17 UTC 20180331: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT user.id AS user_id, user.email_address 
```
One possibility is here:

https://serverfault.com/questions/407612/error-2006-mysql-server-has-gone-away

or

https://stackoverflow.com/questions/12444272/error-2006-mysql-server-has-gone-away-using-python-bottle-microframework-and

**Comment by pjotrp** [comment]
Full error trace (we should not even get there with the new authentication!)

```
ERROR:wqflask.views:.handle_bad_request: 12:21:06 UTC 20180331: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT user.id AS user_id, user.email_address AS user_email_address, user.password AS user_password, user.full_name AS user_full_name, user.organization AS user_organization, user.active AS user_active, user.registration_info AS user_registration_info, user.confirmed AS user_confirmed, user.superuser AS user_superuser \nFROM user \nWHERE user.id = %s'] [parameters: ('None',)]
ERROR:wqflask.views:.handle_bad_request: 12:21:06 UTC 20180331: u'http://gn2-staging.genenetwork.org/'
ERROR:wqflask.views:.handle_bad_request: 12:21:06 UTC 20180331: Traceback (most recent call last):
  File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/staging/gene/wqflask/wqflask/views.py", line 137, in index_page
    return render_template("index_page_orig.html", version=GN_VERSION)
  File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/staging/gene/wqflask/wqflask/templates/index_page_orig.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/staging/gene/wqflask/wqflask/templates/base.html", line 47, in top-level template code
    {% if g.user_session.user_ob %}
  File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/home/staging/gene/wqflask/wqflask/user_manager.py", line 234, in user_ob
    self.db_object = model.User.query.get(self.user_id)
```

**Comment by zsloan** [comment]
Should I still be using
"GN2_PROFILE=/usr/local/guix-profiles/gn2-elasticsearch" when running GN2?
When I ran it with that after pulling the #300 request I got an error:

  File "/home/zas1024/gene/wqflask/wqflask/user_manager.py", line 222, in
> user_ob
>     raise "OBSOLETE: use ElasticSearch instead"

**Comment by pjotrp** [comment]
I put that message in there on purpose. Yes, the GN2_PROFILE should work.

**Comment by zsloan** [comment]
In that case I guess the question is what's causing the error, since I'm
running it with GN2_PROFILE=/usr/local/guix-profiles/gn2-elasticsearch.

This is the entire command being used:
env GN2_PROFILE=/usr/local/guix-profiles/gn2-elasticsearch
TMPDIR=/home/zas1024/tmp WEBSERVER_MODE=DEBUG LOG_LEVEL=DEBUG
SERVER_PORT=5002 GENENETWORK_FILES=/home/zas1024/genotype_files
SQL_URI=mysql://webqtlout:webqtlout@lily.uthsc.edu/db_webqtl
./bin/genenetwork2 ./etc/default_settings.py -gunicorn-dev &>>
/home/zas1024/tmp/test.log &

**Comment by pjotrp** [comment]
Moved to issue #319
