### ISSUE TITLE
GN2 crashed for unknown reason

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#239]
The error is below. I'm not sure what caused this based upon the error alone.

```
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/gnu/store/j8wwk2ab5j1j7c3nkilz0339l3wh5qd2-python2-werkzeug-0.11.2/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/gnu/store/j8wwk2ab5j1j7c3nkilz0339l3wh5qd2-python2-werkzeug-0.11.2/lib/python2.7/site-packages/werkzeug/serving.py", line 185, in execute
    write(data)
  File "/gnu/store/j8wwk2ab5j1j7c3nkilz0339l3wh5qd2-python2-werkzeug-0.11.2/lib/python2.7/site-packages/werkzeug/serving.py", line 153, in write
    self.send_header(key, value)
  File "/gnu/store/kcc3cxnx9l2hbg7pjhxsa0r5yq2j2f38-python-2.7.10/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
```

**Comment by pjotrp** [comment]
Not sure here, but either a network or file system error. Could be hardware, so @lyan6 please check the logs.

**Comment by lyan6** [comment]
Have backup the system logs.

**Comment by pjotrp** [comment]
Reopen if it comes up again. We migrated to gunicorn.
