### ISSUE TITLE
Getting info on GN2 errors with a GN1 page

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#260]
Click on INFO next to CFW published phenotypes and you get

```
http://genenetwork.org/webqtl/main.py?FormID=sharinginfo&GN_AccessionId=None
Mod_python error: "PythonHandler main"

Traceback (most recent call last):

  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/gnshare/gn/web/webqtl/main.py", line 493, in handler
    page = SharingInfoPage.SharingInfoPage(fd)

  File "/gnshare/gn/web/webqtl/dataSharing/SharingInfoPage.py", line 78, in __init__
    self.dict['body'] = sharingInfoObject.getBody(infoupdate="")

  File "/gnshare/gn/web/webqtl/dataSharing/SharingInfo2.py", line 98, in getBody
    return SharingBody.sharinginfo_body_string % (info[9], info[0], info[35], infoupdate, info[38], info[1], info[1], info[10], info[10], info[10], info[11], info[3], info[2], info[5], info[4], info[12], info[7], info[6], info[8], info[22], info[23], info[33], info[24], info[25], info[26], info[27], info[28], info[29], info[30], info[31], htmlfilelist, info[39], info[13], info[14], info[15], info[37], info[16], info[21], info[18], info[19], info[20], info[17], info[35])

TypeError: unsubscriptable object
```

**Comment by pjotrp** [comment]
Similarly when visting http://gn2.genenetwork.org/show_trait?trait_id=20&dataset=CFWPublish click on 'CFW Phenotypes' and there is nothing. Maybe it is a GN2 problem?

**Comment by zsloan** [comment]
This issue was fixed a while back. There was an issue with the link.
