### ISSUE TITLE
ValueError: could not convert string to float: ZNF77

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#284]
http://gn2.genenetwork.org/show_trait?trait_id=4684870&dataset=UMUTAffyExon_0209

The server has no load and the error log
looks like:

```
	ERROR:wqflask.views:.show_trait_page: 13:51:49 UTC 20180211: u'http://gn2.genenetwork.org/show_trait?trait_id=4684870&dataset=UMUTAffyExon_0209
	_RMA'
	ERROR:wqflask.views:.index_page: 13:51:53 UTC 20180211: u'http://gn2.genenetwork.org/'
	ERROR:wqflask.views:.corr_compute_page: 13:51:58 UTC 20180211: u'http://gn2.genenetwork.org/corr_compute'
	INFO:utility.tools:Found: file /home/zas1024/genotype_files/genotype/BXD.geno

	ERROR:wqflask.views:.submit_trait_form: 13:52:27 UTC 20180211: u'http://gn2.genenetwork.org/submit_trait'
	ERROR:wqflask.views:.help: 13:52:55 UTC 20180211: u'http://gn2.genenetwork.org/help'
	ERROR:wqflask.views:.index_page: 13:53:49 UTC 20180211: u'http://gn2.genenetwork.org/'
	ERROR:wqflask.views:.index_page: 13:55:44 UTC 20180211: u'http://gn2.genenetwork.org/'
	ERROR:wqflask.views:.index_page: 13:55:49 UTC 20180211: u'http://gn2.genenetwork.org/'
	ERROR:wqflask.views:.index_page: 13:57:49 UTC 20180211: u'http://gn2.genenetwork.org/'
	ERROR:wqflask.views:.submit_trait_form: 13:57:52 UTC 20180211: u'http://gn2.genenetwork.org/submit_trait'
	ERROR:wqflask.views:.show_temp_trait_page: 13:58:18 UTC 20180211: u'http://gn2.genenetwork.org/show_temp_trait'
	ERROR:wqflask.views:.handle_bad_request: 13:58:18 UTC 20180211: could not convert string to float: ZNF77
	ERROR:wqflask.views:.handle_bad_request: 13:58:18 UTC 20180211: u'http://gn2.genenetwork.org/show_temp_trait'
	ERROR:wqflask.views:.handle_bad_request: 13:58:18 UTC 20180211: Traceback (most recent call last):
		File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
			rv = self.dispatch_request()
		File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
			return self.view_functions[rule.endpoint](**req.view_args)
		File "/home/production/gene/wqflask/wqflask/views.py", line 416, in show_temp_trait_page
			template_vars = show_trait.ShowTrait(request.form)
		File "/home/production/gene/wqflask/wqflask/show_trait/show_trait.py", line 151, in __init__
			self.make_sample_lists()
		File "/home/production/gene/wqflask/wqflask/show_trait/show_trait.py", line 317, in make_sample_lists
			header="%s Only" % (self.dataset.group.name))
		File "/home/production/gene/wqflask/wqflask/show_trait/SampleList.py", line 44, in __init__
			sample = webqtlCaseData.webqtlCaseData(name=sample_name, value=float(self.this_trait[counter-1]))
	ValueError: could not convert string to float: ZNF77
```

So it bombs out but never returns!!

**Comment by zsloan** [comment]
I'm looking into this error from a while back, and there doesn't appear to be a dataset corresponding that name. How was this trait accessed?

There *is* a UMUTAffyExon_0209_RMA, and the same link with the _RMA appended to the dataset name works.

**Comment by zsloan** [comment]
Closing this issue since it no longer seems to exist.
