### ISSUE TITLE
New authentication does not handle collections

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#287]
Log out. Create a collection. Sign in - old collection is still visible. When logged in:

1. Combined search box: POSITION=(chr1 25 30)
2. Select all
3. Add

It bombs out with

```
      GeneNetwork lario:sumo_gn2:2.11-rc1-gn-testing-es-d636315ad  http://localhost:5003/collections/add?traits=1433387_at:HC_M2_0606_P:792cd5161ed90cbbf345,1459553_at:HC_M2_0606_P:8f9a0a63b2f70330133b,1432048_at:HC_M2_0606_P:4ff1b8679aa288f4de68,1458779_at:HC_M2_0606_P:6a8475227fc458d73582,1454782_at:HC_M2_0606_P:7b877756588b67e70149,1446358_at:HC_M2_0606_P:00ad621268c247926645,1433388_at:HC_M2_0606_P:172fbf884bdf7d4f830d,1445156_at:HC_M2_0606_P:d1aaa526951684a60c01 (10:41AM UTC Feb 15, 2018)
       Traceback (most recent call last):
         File "/home/wrk/opt/gn-latest/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
           rv = self.dispatch_request()
         File "/home/wrk/opt/gn-latest/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
           return self.view_functions[rule.endpoint](**req.view_args)
         File "/gnu/export/local/home/wrk/izip/git/opensource/genenetwork/sumo_gn2/wqflask/wqflask/collect.py", line 226, in collections_add
           user_collections = g.user_session.user_ob.user_collections
       AttributeError: 'NoneType' object has no attribute 'user_collections'
```

@fredmanglis see if you can fix this. If it is too hard I can take another look.

**Comment by pjotrp** [comment]
This is for @zsloan. With the new authentication/sessions g.user_session.+user_ob+ does not exist. The user_session has changed - maybe it picks up an old one. Can you see if you can fix this? Please synchronize with the testing tree - I have been pushing fixes to get authentication working.

**Comment by zsloan** [comment]
Yeah, I'll prioritize resolving existing issues related to user
sessions/authentication early this week.

**Comment by zsloan** [comment]
All this stuff with collections/users should be working now.
