### ISSUE TITLE
When you hit a page without parameters it will blow out with an error

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#295]
Try http://gn2.genenetwork.org/show_trait

400 is correct value, but we should (arguably) catch this.

This is in the logs:

```
ERROR:wqflask:Exception on /show_trait [GET]
Traceback (most recent call last):
  File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/production/gene/wqflask/wqflask/views.py", line 431, in show_trait_page
    template_vars = show_trait.ShowTrait(request.args)
  File "/home/production/gene/wqflask/wqflask/show_trait/show_trait.py", line 68, in __init__
    self.trait_id = kw['trait_id']
  File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/werkzeug/datastructures.py", line 406, in __getitem__
    raise exceptions.BadRequestKeyError(key)
BadRequestKeyError: 400: Bad Request
```

**Comment by pjotrp** [comment]
Same for 

- http://gn2.genenetwork.org/gsearch
