### ISSUE TITLE
GN1: compute error

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#333]
Got this error computing correlations using this URL using all three
   methods of correlation

```
   [9]http://gn1.genenetwork.org/webqtl/main.py?sid=ba795cf96a9eb13be17c2bf8d50bfee6c57330d0

Traceback (most recent call last):
  File "/gnshare/gn/web/webqtl/cmdLine/webqtlCmdLine.py", line 94, in ?
    from correlation import CorrelationPage
  File "/gnshare/gn/web/webqtl/cmdLine/../correlation/CorrelationPage.py", line48, in ?
    from correlation import correlationFunction
  File "/gnshare/gn/web/webqtl/cmdLine/../correlation/correlationFunction.py", l
ine 29, in ?
    import rpy2.robjects
  File "build/bdist.linux-x86_64/egg/rpy2/robjects/__init__.py", line 12, in ?
  File "build/bdist.linux-x86_64/egg/rpy2/rinterface/__init__.py", line 66, in ?
  File "build/bdist.linux-x86_64/egg/rpy2/rinterface/rinterface.py", line 7, in ?
  File "build/bdist.linux-x86_64/egg/rpy2/rinterface/rinterface.py", line 4, in
__bootstrap__
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 799, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 1229, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 1249, in _extract_resource
    real_path = manager.get_cache_path(
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 880, in get_cache_path
    self.extraction_error()
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 846, in extract
ion_error
    raise err
ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 13] Permission denied: '/home/pjotr/.python-eggs'

The Python egg cache directory is currently set to:

  /home/pjotr/.python-eggs

Perhaps your account does not have write access to this directory?  You can change the cache directory by setting the PYTHON_EGG_CACHE environment variable to point to an accessible directory.
```

**Comment by pjotrp** [comment]
@robwwilliams writes:   The reason may be that markers from the newer 2017 genotypes are NOT in
   the GN1/GN2 database. This is a design issue—we need the genotypes
   both in .geno files for rapid computation, but we also need them in the
   database to use as cofactors etc.
