### ISSUE TITLE
Bug: Cannot delete a collection from inside a collection

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#397]
#### Description

Once you are inside a collection, you can't delete the collection. Below is the full stack trace:

<details>
<summary>Click to toggle full stack trace</summary>
<pre>
  GeneNetwork penguin2:genenetwork2:2.11-rc2-use-guix-datatables-extensions-dependency-e0454d8a2  http://gn2-test2.genenetwork.org/export_traits_csv (10:50PM UTC Jun 04, 2020)
       Traceback (most recent call last):
         File "/home/bonfacem/opt/genenetwork2/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
           rv = self.dispatch_request()
         File "/home/bonfacem/opt/genenetwork2/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
           return self.view_functions[rule.endpoint](**req.view_args)
         File "/home/bonfacem/gn2-bonface/genenetwork2/wqflask/wqflask/views.py", line 434, in export_traits_csv
           csv_data, file_name = export_traits.export_search_results_csv(request.form)
         File "/home/bonfacem/gn2-bonface/genenetwork2/wqflask/wqflask/export_traits.py", line 14, in export_search_results_csv
           table_data = json.loads(targs['export_data'])
         File "/home/bonfacem/opt/genenetwork2/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
           return _default_decoder.decode(s)
         File "/home/bonfacem/opt/genenetwork2/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
           obj, end = self.raw_decode(s)
         File "/home/bonfacem/opt/genenetwork2/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
           return self.scan_once(s, idx=_w(s, idx).end())
       JSONDecodeError: Expecting value: line 1 column 1 (char 0)

</pre>
</details>

#### To Reproduce

- Create a collection
- Go to the list of collections on http://gn2.genenetwork.org/collections/list
- Click on of the collections listed in the table
- Click on the <kbd>Collection</kbd> button which is next to <kbd>Delete Rows</kbd> button

#### Expected Behavior

The collection should be deleted

#### Screenshots

N/A

#### Environment setup (please complete the following information):
- OS: arch linux
- Browser: Firefox v75.0

#### Additional context

N/A

**Comment by fredmanglis** [comment]
@BonfaceKilz Tried this out, and it seems to be fixed at this point in time (2022-03-23T10:19+03:00UTC). I am closing this as fixed.

In case this is not satisfactory, please open an issue in the gemtext issue tracker and link it to this issue.
