### ISSUE TITLE
Build: Migrate from Python2 to Python3

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#398]
#### Description

Right now GN2 is running on Python2; We need to migrate it to Python 3 (preferrably 3.6 because that's the default Python in Ubuntu LTS and related distro's). For E2E, improve Mechanical Rob, and work with @zsloan and @BonfaceKilz to iron tests out.

**Comment by BonfaceKilz** [comment]
Useful resource: https://docs.python.org/3/howto/pyporting.html

**Comment by BonfaceKilz** [comment]
When I run python with the following alias:

```bash
alias runpython="env GN2_PROFILE=/home/bonface/opt/genenetwork2 TMPDIR=/home/bonface/tmp SERVER_PORT=5004 GENENETWORK_FILES=/home/bonface/gnu/data/gn2_data/ /home/bonface/projects/genenetwork2/bin/genenetwork2 /home/bonface/projects/genenetwork2/etc/default_settings.py -c"
```

and get into the REPL:

```bash
>>> import wqflask
>>> dir(wqflask)
['Flask', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'absolute_import', 'api', 'app', 'collect', 'comparison_bar_chart', 'correlation', 'correlation_matrix', 'ctl', 'database', 'division', 'do_search', 'docs', 'export_traits', 'external_tools', 'formatting', 'group_manager', 'gsearch', 'heatmap', 'interval_analyst', 'jinja2', 'logger', 'logging', 'marker_regression', 'model', 'network_graph', 'news', 'parser', 'pbkdf2', 'print_function', 'resource_manager', 'router', 'search_results', 'show_trait', 'snp_browser', 'submit_bnw', 'sys', 'update_search_results', 'user_login', 'user_session', 'views', 'wgcna', 'wqflask']
>>>
```

However, from a unittest in **test/unittest/base/test_data_set.py** that looks like:

```python
import unittest

import wqflask
print dir(wqflask)

class TestDataSet(unittest.TestCase):
    def test_add(self):
        self.assertEqual(3, 4)

```

the output for `dir(wqflask)` is different. I get:

```
TMPDIR=/home/bonface/tmp
PYTHONPATH=/home/bonface/projects/genenetwork2/wqflask:/home/bonface/opt/genenetwork2/lib/python2.7/site-packages
RUNNING COMMAND -m unittest discover test -t /home/bonface/projects/genenetwork2/ -v
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
test_add (test.unittest.base.test_data_set.TestDataSet) ... FAIL

======================================================================
FAIL: test_add (test.unittest.base.test_data_set.TestDataSet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bonface/projects/genenetwork2/test/unittest/base/test_data_set.py", line 9, in test_add
    self.assertEqual(3, 4)
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
```

Notice the output of `dir(wqflask)`. I'm trying to write some basic unittests.

When I update **test/unittest/base/test_data_set.py** to:

```python
import unittest

import wqflask.base.data_set
print dir()

class TestDataSet(unittest.TestCase):
    def test_add(self):
        self.assertEqual(3, 4)
```

and run:  **runpython -m unittest discover test -t /home/bonface/projects/genenetwork2/ -v** with the aforementioned alias, I get the following trace:

```
RUNNING COMMAND -m unittest discover test -t /home/bonface/projects/genenetwork2/ -v
test.unittest.base.test_data_set (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test.unittest.base.test_data_set (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.unittest.base.test_data_set
Traceback (most recent call last):
  File "/gnu/store/cj2xkwigzcdd174hpanj18dp2p39mprv-python2-2.7.17/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/gnu/store/cj2xkwigzcdd174hpanj18dp2p39mprv-python2-2.7.17/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/bonface/projects/genenetwork2/test/unittest/base/test_data_set.py", line 3, in <module>
    import wqflask.base.data_set
  File "/home/bonface/projects/genenetwork2/wqflask/base/__init__.py", line 2, in <module>
    import data_set
  File "/home/bonface/projects/genenetwork2/wqflask/base/data_set.py", line 42, in <module>
    from base import webqtlConfig
  File "base/__init__.py", line 2, in <module>
    import data_set
  File "base/data_set.py", line 42, in <module>
    from base import webqtlConfig
  File "base/webqtlConfig.py", line 11, in <module>
    from utility.tools import valid_path, mk_dir, assert_dir, assert_writable_dir, flat_files, TEMPDIR
  File "utility/tools.py", line 7, in <module>
    from wqflask import app
ImportError: cannot import name app
```

@zsloan could you have any work-around or ideas for the above? How we import things is a bit weird- I've been struggling with :point_up_2: for some time now- since we `cd` into wqflask in addition to adding it to the *PYTHONPATH*. I reckon once I can wrangle out a bunch of test cases that are green, it'd be a big win for us.

**Comment by BonfaceKilz** [comment]
The methods for `python2-htmlgen` seem to have changed in python3's `python-htmlgen`, so I'm working on updating those.
