### ISSUE TITLE
Build: Add CI

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#416]
#### Description

Add CI to github repository. Right now, you have to run tests manually to confirm a working build. The CI should be able to run Mechanical Rob and existing unittests and show a green when creating or updating a PR. Suggestions for CI tools are:

- Github Action
- Circle CI
- Travis

**Comment by BonfaceKilz** [comment]
Will work on this once done with https://github.com/genenetwork/genenetwork2/issues/398

**Comment by pjotrp** [comment]
If you use one that allows for Docker containers we can use Guix to provide those. The dependencies will be hardest for local test running.

**Comment by BonfaceKilz** [comment]
I'll create a mirror of this repo on GH that's a detached fork and do all my CI testing there.

**Comment by BonfaceKilz** [comment]
So I've been able to create a docker container that works. What I've been trying to do is decouple the unittests from the Redis instance.

<details>
<summary><b>Click to see errors</b></summary>
<pre>
======================================================================
ERROR: tests.base.test_trait (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.base.test_trait
Traceback (most recent call last):
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "tests/base/test_trait.py", line 6, in <module>
    from base.trait import GeneralTrait
  File "base/trait.py", line 11, in <module>
    from base.webqtlConfig import PUBMEDLINK_URL
  File "base/webqtlConfig.py", line 11, in <module>
    from utility.tools import (valid_path,
  File "utility/tools.py", line 8, in <module>
    from wqflask import app
  File "wqflask/__init__.py", line 23, in <module>
    from wqflask.api import router
  File "wqflask/api/router.py", line 16, in <module>
    from wqflask.api import correlation, mapping, gen_menu
  File "wqflask/api/correlation.py", line 11, in <module>
    from base import data_set
  File "base/data_set.py", line 22, in <module>
    from db.call import fetchall, fetchone, fetch1
  File "db/call.py", line 8, in <module>
    from utility.tools import USE_GN_SERVER, LOG_SQL, GN_SERVER_URL
ImportError: cannot import name USE_GN_SERVER


======================================================================
ERROR: tests.base.test_data_set (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.base.test_data_set
Traceback (most recent call last):
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "tests/base/test_data_set.py", line 6, in <module>
    from wqflask import app
  File "wqflask/__init__.py", line 23, in <module>
    from wqflask.api import router
  File "wqflask/api/router.py", line 16, in <module>
    from wqflask.api import correlation, mapping, gen_menu
  File "wqflask/api/correlation.py", line 11, in <module>
    from base import data_set
  File "base/data_set.py", line 174, in <module>
    Dataset_Getter = DatasetType(r)
  File "base/data_set.py", line 96, in __init__
    data = self.redis_instance.get("dataset_structure")
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 1071, in get_connection
    connection.connect()
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.


======================================================================
ERROR: tests.wqflask.marker_regression.test_display_mapping_results (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.wqflask.marker_regression.test_display_mapping_results
Traceback (most recent call last):
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "tests/wqflask/marker_regression/test_display_mapping_results.py", line 4, in <module>
    from wqflask.marker_regression.display_mapping_results import (
  File "wqflask/__init__.py", line 23, in <module>
    from wqflask.api import router
  File "wqflask/api/router.py", line 16, in <module>
    from wqflask.api import correlation, mapping, gen_menu
  File "wqflask/api/correlation.py", line 11, in <module>
    from base import data_set
  File "base/data_set.py", line 174, in <module>
    Dataset_Getter = DatasetType(r)
  File "base/data_set.py", line 96, in __init__
    data = self.redis_instance.get("dataset_structure")
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 1071, in get_connection
    connection.connect()
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 543, in connect                                  
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.


======================================================================
ERROR: tests.wqflask.api.test_gen_menu (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.wqflask.api.test_gen_menu
Traceback (most recent call last):
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "tests/wqflask/api/test_gen_menu.py", line 5, in <module>
    from wqflask.api.gen_menu import gen_dropdown_json
  File "wqflask/__init__.py", line 23, in <module>
    from wqflask.api import router
  File "wqflask/api/router.py", line 16, in <module>
    from wqflask.api import correlation, mapping, gen_menu
  File "wqflask/api/correlation.py", line 11, in <module>
    from base import data_set
  File "base/data_set.py", line 174, in <module>
    Dataset_Getter = DatasetType(r)
  File "base/data_set.py", line 96, in __init__
    data = self.redis_instance.get("dataset_structure")
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 1071, in get_connection
    connection.connect()
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.


======================================================================
ERROR: tests.utility.test_hmac (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.utility.test_hmac
Traceback (most recent call last):
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "tests/utility/test_hmac.py", line 7, in <module>
    from utility.hmac import data_hmac
  File "utility/hmac.py", line 7, in <module>
    from wqflask import app
  File "wqflask/__init__.py", line 23, in <module>
    from wqflask.api import router
  File "wqflask/api/router.py", line 16, in <module>
    from wqflask.api import correlation, mapping, gen_menu
  File "wqflask/api/correlation.py", line 11, in <module>
    from base import data_set
  File "base/data_set.py", line 174, in <module>
    Dataset_Getter = DatasetType(r)
  File "base/data_set.py", line 96, in __init__
    data = self.redis_instance.get("dataset_structure")
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 1071, in get_connection
    connection.connect()
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.


======================================================================
ERROR: tests.utility.test_authentication_tools (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.utility.test_authentication_tools
Traceback (most recent call last):
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/gnu/store/5a0jj0r2l9ag0rs93f751lsisimz9nn5-python2-2.7.17/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "tests/utility/test_authentication_tools.py", line 5, in <module>
    from utility.authentication_tools import check_resource_availability
  File "utility/authentication_tools.py", line 8, in <module>
    from utility.redis_tools import get_redis_conn
  File "utility/redis_tools.py", line 8, in <module>
    from utility.hmac import hmac_creation
  File "utility/hmac.py", line 7, in <module>
    from wqflask import app
  File "wqflask/__init__.py", line 23, in <module>
    from wqflask.api import router
  File "wqflask/api/router.py", line 16, in <module>
    from wqflask.api import correlation, mapping, gen_menu
  File "wqflask/api/correlation.py", line 11, in <module>
    from base import data_set
  File "base/data_set.py", line 174, in <module>
    Dataset_Getter = DatasetType(r)
  File "base/data_set.py", line 96, in __init__
    data = self.redis_instance.get("dataset_structure")
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 1071, in get_connection
    connection.connect()
  File "/home/bonface/opt/genenetwork2/lib/python2.7/site-packages/redis/connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.


----------------------------------------------------------------------
Ran 28 tests in 0.003s

FAILED (errors=6)
</pre>
</details>

@zsloan It's a good idea to think about how tightly coupled things get to prevent things like that ^^. Ideally unittests shouldn't care whether Redis or some other  service is running. So I'm trying to work around that. Hope it won't eat much time.

Other than that, once I do that ^^, our CI will be unittests running in a guix-generated docker container :). That step is trivial imo.

**Comment by zsloan** [comment]
It shouldn't be hard for me to deal with the specific situation you mention, since
there's already some code there for when Redis is empty (which would just
need to also account for when Redis isn't running at all), but I'm less
sure about how to deal with the relationship between Redis and
authentication (other than just barring access to all resources if Redis
isn't running).

**Comment by BonfaceKilz** [comment]
First running CI here: https://github.com/BonfaceKilz/Genenetwork2-Mirror/runs/1145792655?check_suite_focus=true. I'd need to fine tune somethings before adding that here :)

I'll work out how to run Mechanical Rob later...
